name: uip_tv_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.3.beta


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

#  fonts:
#    - family: Akatab
#      fonts:
#        - asset: asset/fonts/Akatab-Regular.ttf
#        - asset: asset/fonts/Akatab-Italic.ttf
#
#    - family: Roboto
#      fonts:
#        - asset: asset/fonts/Roboto-Medium.ttf
#        - asset: asset/fonts/Roboto-Regular.ttf


